### ISSUE TITLE
tracking issue for chumsky compat

### ISSUE THREAD

**Issue by nothendev** [Implodent/AOTT#1]
this is the tracking issue for all work on feature parity and/or compatibility with chumsky

idea is to have full feature parity without memory leaks (im looking at you, recursive) and outright computer explosions (ironic because Parser::explode)

- combinators:
  - [x] \*_map (try_map, filter_map etc.), select macro
  - [x] Parser::then (ehhh only for compat), .then\_ignore, .ignore\_then
  - [x] recursive (+ .clone and memleak tests)
         please just clone it as a weak pleaseeeeeeeeeeeee
  - [ ] separated_by
- [ ] ALL text builtins
  - [x] ascii
    - [x] ident, keyword

**Comment by nothendev** [comment]
[text] https://github.com/Implodent/AOTT/commit/12911f06f85cef0f26b024a4b59042d8a8dcaf05 affects:
- ident (added)
- keyword (added)

**Comment by nothendev** [comment]
added to v0.2.0

**Comment by nothendev** [comment]
blocker of this and, really, the entire project is #4

**Comment by nothendev** [comment]
YEEEEEEEEEEEEEEEEEE

I FIXED IT AWEAIWEJAOPWEJPOAWJEPOWAJPEAJWOIEJAWJEIAW

b2e0c6e
