### ISSUE TITLE
tracking issue for internal docs

### ISSUE THREAD

**Issue by nothendev** [Implodent/AOTT#2]
so there is a directory for internal docs: docs/contrib

this issue should contain all discussion that is intended to be public (outside of the scope of the internal communication channels like *that* discord server) about internal docs, and documentation in general

- [ ] document project structure
- [ ] document how "internal" (#[doc(hidden)]) apis work, like the inputs api and the explode api
- [ ] document how to control the Input, save offsets and rewind back to those saved offsets
- [ ] document how to do tests
- [ ] document how to implement Parser by hand and how to make new primitives / combinators (please dont call them that please)

**Comment by nothendev** [comment]
these ones are gonna be real hard cus sometimes i dont know what the code i wrote 30s ago does even though i didnt copy it from somewhere lol

**Comment by abs0luty** [comment]
Yeah, so we probably need to somehow minimally stabilize the code first and only then start writing docs.

**Comment by nothendev** [comment]
there are almost no internals, closing.
