### ISSUE TITLE
tracking issue for error recovery

### ISSUE THREAD

**Issue by nothendev** [Implodent/AOTT#3]
this issue tracks the implementation of error recovery and is intended for discussion of potential ideas, strategies etc.

# keep in mind this is paused until full feature parity with chumsky (#1)

below is the todo list for making error recovery as a feature:

- [ ] implement sensible infrastructure for error recovery
  - [ ] something like a .recover method on ParserExtras that could either call a builtin strategy or do its own thing
- [ ] implement builtin strategies:
  - [ ] the noop strategy - just dont do anything
  -  [ ] slow and steady - rewind. parse. rewind again. parse.
  - [ ] custom - a way to do error recovery youself (**VERY IMPORTANT!!**)
- [ ] test the builtin strategies to hell to be sure they work fr and dont explode on an edgecase
- [ ] make internal documentation for implementing builtin strategies
- [ ] document the user facing api and how to even do error recovery

**Comment by abs0luty** [comment]
I'll add some more strategies to error recovering in the issue later and I'm probably gonna start closing it in 2 days.

**Comment by nothendev** [comment]
> I'll add some more strategies to error recovering in the issue later and I'm probably gonna start closing it in 2 days.

like implementing?

and also could you please write out your ideas on the strategies?

**Comment by nothendev** [comment]
added to v0.3.0

this should be added before 0.3 is tagged;
if it happens to exist and be stable enough that you could just add a feature flag before 0.2 it will be moved to the 0.2 milestone and included in 0.2

**Comment by nothendev** [comment]
moved to 0.4, because 0.3 will be for the redesign and other major stuffs
